mizarc/bell-claims

.idea/.name, src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/ClaimManagementMenu.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/EditToolMenu.kt
Players shouldn't be able to place items into GUI menus as doing so would consume the items placed into them. By simply disallowing interactions by default on each menu, this shouldn't be possible.
=> Fix GUIs consuming items placed into them

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/persistence/claims/ClaimFlagRepositorySQLite.kt, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/persistence/claims/ClaimPermissionRepositorySQLite.kt, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/persistence/claims/PlayerAccessRepositorySQLite.kt, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/PlayerPermissionServiceImpl.kt
This was due to the reference being passed from the repository rather than the value, causing a concurrent modification error as the loop attempts to keep going while the set it is looping through is being modified.
A changelog file has also been provided to keep track of changes before it gets confusing.
=> Deselecting all permissions/flags only deselecting one before throwing error

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/EditToolListener.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/EditToolMenu.kt
Simply just needed to call the visualiser refresh method when clicking the button.
=> Visualiser not updating when changing edit tool mode

CHANGELOG.md, README.md, src/main/kotlin/dev/mizarc/bellclaims/BellClaims.kt, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/playerlimit/SimplePlayerLimitServiceImpl.kt, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/playerlimit/VaultPlayerLimitServiceImpl.kt, src/main/resources/plugin.yml, src/test/kotlin/dev/mizarc/bellclaims/infrastructure/services/PlayerLimitServiceImplTest.kt, src/test/kotlin/dev/mizarc/bellclaims/infrastructure/services/playerlimit/SimplePlayerLimitServiceImplTest.kt, src/test/kotlin/dev/mizarc/bellclaims/infrastructure/services/playerlimit/VaultPlayerLimitServiceImplTest.kt
Having Vault and a registered chat API provider could stop certain server owners from wanting to use this plugin. While it is still recommended to have it installed alongside in order to gain full functionality over claim limits, it should only be an optional requirement.
=> Reconfigure project to only require Vault as a soft dependency

build.gradle.kts
Removes the relocation in the `shadowJar` step and updates IF to version 0.10.15
=> Fix build for Java 21 / Minecraft 1.21

src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PermissionBehaviour.kt
Adds a handler for the entity breed event. This is a very simple handler which just checks the position of one entity (which might not be the right choice). It also only allows breeding with the *"Build"* permission. It might be nicer to rename the *"MobShear"* permission and put this handler into that.
Oh and can I just say: I like this codebase! It's nice and professional and the way claim interactions are handled is really clean. Great work!
=> Add `EntityBreedEvent` handler

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PermissionBehaviour.kt, src/main/kotlin/dev/mizarc/bellclaims/utils/PermissionDisplay.kt, src/test/kotlin/dev/mizarc/bellclaims/infrastructure/services/PlayerPermissionServiceImplTest.kt
Players generally found no use for the separation of mob permissions. It may be a better idea to just merge them all into one "Husbandry" permission that allows players to do anything pertaining to the maintenance of farm animals.
=> Recategorise all passive mob permissions into one

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/ClaimDestructionListener.kt
The bell attachment checks were done incorrectly so it would always check the north and south directions regardless of if the bell was attached to a block in that direction.
=> Fixed ability to break blocks to the north and south of bell

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PermissionBehaviour.kt
Players that do not have any permissions in a claim are still able to right click dragon eggs from inside the claim, which causes the dragon egg to teleport. This is now part of the build permission.
=> Add protection for dragon egg being teleported from player right clicking

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PermissionBehaviour.kt
Players are able to edit signs using dyes to change the colour as well as use glow ink to make it glow. Protection for this is now handled by the sign edit permission.
=> Added protection against the usage of dyes and glow ink on signs

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PermissionBehaviour.kt
Players were able to shear pumpkins in protected claims. This action is now protected by the build permission, as it is a permanent change to the world.
=> Added protection against shearing pumpkins

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PermissionBehaviour.kt
Player were able to use shears or bottles to harvest honey and honeycombs from beehives. Permission to do this is now behind the husbandry permission.
The first change of shearing hives was accidentally pushed to main by me (oops). Should've been put in this pull request.
=> Added protection against beehive harvesting

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PermissionBehaviour.kt
Players were able to make use of composters inside someone's protected claim. This is now protected behind the display manipulate permission, as it is changing the temporary state of a placed block.
=> Added protection against composter usage

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/FlagBehaviour.kt
Bees should not be affected by mob griefing since the act of producing honey is not a very destructive action. Please let the bees do their work.
=> Fixed bees unable to produce honey while mob griefing flag is off

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/domain/flags/Flag.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/FlagBehaviour.kt
This deals with issue #19 where sand and other falling block types do not fall in claims. The check for entities changing block state has been modified to be a blacklist of "Monster" rather than a whitelist of allowed types, which should reduce issues like these, but may also open up more issues in the future. Seems like a good enough compromise for now.
=> Fixed falling blocks not falling in claims

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/domain/flags/Flag.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/FlagBehaviour.kt
Zombies should not be able to break down doors with the "Mob Griefing" flag disabled. With this change zombies can't break down doors but they will still make breaking noises and look like they're breaking down the door. Don't be afraid, they can't get in.
=> Added protection against zombies breaking down doors

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/ClaimListMenu.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/ClaimManagementMenu.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/EditToolMenu.kt
Players would have their items taken by the menu and deleted after shift clicking it into the menu. This simply blocks all shift click events on the player's own inventory, but needs to be done for every single menu created in the future.
=> Fixed items being consumed by menu from shift clicking

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PermissionBehaviour.kt, src/main/kotlin/dev/mizarc/bellclaims/utils/PermissionDisplay.kt
Here are all the things players were able to do prior to the addition of this permission:
- Use flint and steel on tnt.
- Shoot tnt with flaming projectile.
- Shoot minecart tnt with flaming projectile.
- Damage end crystal causing it to explode.
- Use bed outside of the overworld causing it to explode.
- Use respawn anchor outside of the nether causing it to explode.
This request puts all of these actions into the one "Detonate" permissions that claim owners can specifically grant to players.
=> Added protections against various types of explosives in a new "Detonate" permission

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PermissionBehaviour.kt
Players should not be able to eat cake without permission. The current permission it is set to is "Display Manipulate", but this is a little contested since eating a cake removes it from the world, while other display manipulate accesses are reversible. "Build" doesn't really make sense either though since needing to give someone build permissions just to eat cake seems overkill. This is a good placement for now.
=> Added protection for cake eating

CHANGELOG.md, CONTRIBUTING.md, src/main/kotlin/dev/mizarc/bellclaims/utils/PermissionDisplay.kt
This sounds more natural for the end user and less like an internal name. Notable changes include:
- Sign Edit -> Edit Signs
- Villager Trade -> Trade Villagers
- Vehicle Deploy -> Deploy Vehicles
Display Manipulate has also been simplified to just Manipulate.
=> Change the display name of permissions to use verbs first

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/domain/partitions/Partition.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/EditToolListener.kt
There's no way of knowing how many claim blocks you have left until the selection you're making is too large. This addresses the issue by adding the remaining amount on any claim block resize action.
The display amount was also incorrect when the claim resize was too large and the player did not have enough blocks, which has also been fixed.
=> Show claim block remaining amount on claim resizing

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/BellClaims.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/ClaimDestructionListener.kt
Server moderators need a way to get rid of claim bells that are owned by other players. This allows bells to be broken the same way as usual when the claim override is being used.
=> Added ability to break claim bells with claim override

CHANGELOG.md, build.gradle.kts, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/persistence/claims/ClaimPermissionRepositorySQLite.kt, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/persistence/claims/PlayerAccessRepositorySQLite.kt, src/main/resources/plugin.yml
Since the permissions "MobHurt", "MobShear", and "MobLeash" do not exist anymore, loading from the database creates errors which prevents the plugin from loading outright.
These values will remain in database, but will be ignored. Players are expected to replace their existing claims with the Husbandry permission manually. Nothing will be replaced to keep it safe.
=> Hotfix for database permission enum errors on launch

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PermissionBehaviour.kt
Item frames were not protected against projectiles since an incorrect check was added which bypassed the projectile protections that were added last major version.
Glow item frames had even less protections since there were no checks for placing frames in claims as well as putting items into the frames.
=> Fixed item frame protections not being fully effective

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PermissionBehaviour.kt
Since redstone is also handled by its own permission, the ability to break it was also handled as part of the redstone permission, despite being able to place redstone with the build permission. Redstone placing and breaking is now fully handled by the build permission.
=> Fixed unable to break redstone despite having build permissions

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PermissionBehaviour.kt, src/main/kotlin/dev/mizarc/bellclaims/utils/PermissionDisplay.kt
Players can grief claims by going in with a bad omen effect to get their villagers killed. This stops it dead in its tracks, but it does also remove the effect entirely. Might come up with a solution for this later if possible.
=> Added new raid protection permission

CHANGELOG.md, build.gradle.kts, src/main/resources/plugin.yml
Due to changes in MC 1.21.1, the GUIs stopped working entirely preventing you from doing pretty much anything. All this needed to fix was an update to the Inventory Framework dependency to version 1.10.17.
=> Fixed GUI interaction errors in MC 1.21.1

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt, src/main/kotlin/dev/mizarc/bellclaims/utils/ClaimFlagDisplay.kt
Rather than blocking all piston functionality inside the claim, this new system checks to see if the piston that is affecting the claim block is outside of the claim. This includes all blocks moved as well as the piston head itself.
=> Changed piston flag behaviour to only cancel pistons used from outside the claim

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PermissionBehaviour.kt
Due to the use of the generic player interaction event to block bucket fluid place usage, it only covered the use of placing fluids directly on blocks. Players were able to bypass this by clicking through an entity, which doesn't count as placing on a block but still takes into account the cursor position to place the fluid.
=> Fixed bypassing protections when placing fluids by clicking through entities

.idea/modules.xml, .idea/modules/BellClaims.main.iml, .idea/modules/BellClaims.test.iml, CHANGELOG.md, build.gradle.kts, settings.gradle.kts, src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PermissionBehaviour.kt, src/main/resources/plugin.yml
Thought this was a bug at first, then realised I never even implemented it in the first place. This uses the same system as preventing players from placing item frames, but applied to paintings
=> Added protection against placing paintings in claims

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/PartitionServiceImpl.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/EditToolListener.kt
The previous size was supposed to be 5x5, but turned out to be 7x7 due to it not counting the claim border itself. The maths behind this still needs to be tweaked, and will be configurable in the future. For now the new absolute minimum will be 3x3.
=> Tweaked minimum partition size to 3x3

CHANGELOG.md, build.gradle.kts, src/main/kotlin/dev/mizarc/bellclaims/domain/partitions/Area.kt, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/PartitionServiceImpl.kt, src/main/resources/plugin.yml, src/test/kotlin/dev/mizarc/bellclaims/infrastructure/services/PartitionServiceImplTest.kt
This should not be possible at all, but only presented itself as a problem once the claim limit was set to 3x3. Doesn't happen with any other larger limit, but it exposed a fatal math flaw in the area calculations.
As a result, this broke visualisations as well as the partition itself, having to resolve it by removing the partition.
=> Fixed the creation of 1 block wide partitions

src/main/kotlin/dev/mizarc/bellclaims/domain/flags/Flag.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt
This pull request solves the problem where skeletons could be used to grief users item frames and paintings inside a claim. An example of how this could be abused was putting a skeleton in boat, driving it to inside a claim and then making the skeleton shoot in the direction of the item frame / painting. This pull request makes this mechanic available under mob griefing.
Video will be send on discord to show the functionality of this hotfix.
=> Disable skeleton griefing Item Frames / Paitings

src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/PermissionBehaviour.kt
Before this hotfix a user would be able to take a horse (Mountable entity) and jump on other peoples farmland to destory it. With this hotfix on an entity interact event there will be looked if that entity contains an passenger. If the entity does and the passenger is a player check for the players permission to build. If the player does not have permission the event will be cancelled otherwise it will contiue.
=> Check horse passenger for permission

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/PermissionBehaviour.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/ClaimInteractListener.kt
Claims are not protected from multiblocks if the multiblock source is placed outside the claim and the rest of the structure spawns inside the claim. This required a bit of an overhaul of the claim location detection system to take in a list of locations rather than the one source location for a given event.
Protection priority was a much simpler change, with it being changed from NORMAL to LOWEST. This effectively overrides every other plugin so that the protections are always applied. May cause conflicts, but is the most effective solution.
=> Fixed multiblock protection & protection priority

src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt
Any "Monster" class hostile mob is now unable to damage entities that are either the player, or other "Monster" class mob. This also collaterally solves the issue of #52 in the process.
=> Protect passive mobs from direct hits by hostile mobs

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/ClaimListMenu.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/ClaimManagementMenu.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/EditToolMenu.kt
This resolves the issue where if a player shift right clicks an item in their own inventory while inside of a menu, the item gets moved into the menu and cannot be retrieved. This effectively deletes the item.
=> Fixed shift right clicking deleting player's items in menus

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/domain/flags/Flag.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/ClaimManagementMenu.kt, src/main/kotlin/dev/mizarc/bellclaims/utils/ClaimFlagDisplay.kt, src/main/resources/lang_EN.yml
This stops players from being able to use dispensers to dispense fluids, boats, and other entities such as armour stands into a claim. It allow affects general item dropping, but having a whitelist for specific items seems like too much of a hassle for very little gain.
=> Added new flag to handle dispenser protection

src/main/kotlin/dev/mizarc/bellclaims/domain/flags/Flag.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/ClaimManagementMenu.kt, src/main/kotlin/dev/mizarc/bellclaims/utils/ClaimFlagDisplay.kt, src/main/resources/lang_EN.yml
New "Sponge Absorb" claim flag has been added, which specifically targets using sponges outside the claim in a body of water that would affect the part of the water that is inside the claim.
=> Added protection against using sponge to drain claim fluids

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/domain/flags/Flag.kt, src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/PermissionBehaviour.kt, src/main/kotlin/dev/mizarc/bellclaims/utils/ClaimFlagDisplay.kt, src/main/resources/lang_EN.yml
This is a double whammy, which covers separate protections for natural and player generated lightning.
Natural lightning is covered by the new "Lightning Damage" flag, which disallows lightning from being able to cause damage and set claim blocks alight.
Player generated lightning is usually caused by tridents enchanted with channeling. While ideally this should only stop the damage being done to passive mobs, I couldn't find a way to control lightning that fine grained, so it just doesn't do damage altogether. The trident will still do damage to the target, and the lightning will still flash briefly, but no additional damage is done by the lightning.
=> Add various lightning protections for flag and permission

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/BellClaims.kt, src/main/kotlin/dev/mizarc/bellclaims/domain/flags/Flag.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/BlockLaunchListener.kt, src/main/kotlin/dev/mizarc/bellclaims/utils/ClaimFlagDisplay.kt, src/main/resources/lang_EN.yml
Falling blocks can be utilised to grief a claim, as players are able to set up block launchers to launch a falling block from outside a claim into a claimed area. This protection denies their ability to do so, dropping the falling block as an item if it lands inside of a claim.
=> Added new protection flag against falling block launching

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/domain/flags/Flag.kt, src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/PermissionBehaviour.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/ClaimManagementMenu.kt
This is a protection that covers both a permission and a flag:
The permission element prevents player thrown potions from affecting passive mobs as a means to grief. This is covered by the husbandry permission.
The flag element prevents dispensed potions from affecting both passive mobs and players. The reason why it shouldn't affect players is because with player thrown potions, the intent is to keep the PVP element to it, as you can kill the player to stop them from throwing potions at you. With dispensers, the player who set up the dispenser could put it down in a protected area, removing your ability to stop the source of the potions.
=> Added protection against splash and lingering potions

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/PermissionBehaviour.kt, src/main/kotlin/dev/mizarc/bellclaims/utils/PermissionDisplay.kt, src/main/resources/lang_EN.yml
This is a pretty simple permission that does what it says on the tin. Players who do not have this permission cannot use beds or respawn anchors in the claim.
=> Added protection against sleeping in beds or setting spawn points at respawn anchors

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/BellClaims.kt, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/persistence/Config.kt, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/ClaimWorldServiceImpl.kt, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/PartitionServiceImpl.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/EditToolListener.kt, src/main/resources/config.yml, src/test/kotlin/dev/mizarc/bellclaims/infrastructure/services/ClaimWorldServiceImplTest.kt, src/test/kotlin/dev/mizarc/bellclaims/infrastructure/services/PartitionServiceImplTest.kt
This allows administrators to change what these values should be server-wide.
=> Add minimum partition and initial claim size options in the config

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/BellClaims.kt, src/main/kotlin/dev/mizarc/bellclaims/domain/partitions/Area.kt, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/persistence/partitions/PartitionRepositorySQLite.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/commands/ClaimCommand.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/commands/InfoCommand.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/commands/PartitionsCommand.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/commands/TrustListCommand.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/ClaimBellListener.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/ClaimInteractListener.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/EditToolListener.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/EditToolRemovalListener.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/ClaimManagementMenu.kt, src/main/kotlin/dev/mizarc/bellclaims/utils/ItemStackExtensions.kt
An issue occurs where players are sometimes able to bypass the player registration process, causing their player state to be null. In instances like these, the player state is created when it needs to be used rather than trying to brute force it and returning null.
Various other null based issues have been solved, ranging from the getting of items, claims, and partitions that may return null.
=> Hotfixed issue of player state being returned as null

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/ClaimDestructionListener.kt
Straightforward issue, straightforward fix. All that needed to be done is to delete the specific bell in the inventory with the specific metadata associated with the bell when the bell block is broken.
=> Fixed bell duplication when move item is in inventory while breaking bell

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/PartitionServiceImpl.kt
This fixes the issue of not being able to append a new partition to a claim if the partition it is being attached to is on the edge of a chunk border. This is due to the function not grabbing adjacent chunks, leading to it not detecting the adjacent partition at all.
=> Fixed inability to append partition on chunk border

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/BellClaims.kt, src/main/kotlin/dev/mizarc/bellclaims/domain/players/PlayerState.kt, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/persistence/Config.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/EditToolVisualisingListener.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/visualisation/Visualiser.kt, src/main/resources/config.yml
This resolves potential lag when a player decides to rapidly equip and unequip the claim tool, which causes the visualiser to recalculate itself every single time it is triggered. A value can be modified in the config to set how long the visualiser remains before being hidden.
=> Added configurable visualiser delay period on claim tool unequip

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/domain/flags/Flag.kt, src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/PermissionBehaviour.kt
This protects against pot breakage by players that is protected by the build permission, and against mobs that is protected by the mob griefing flag.
=> Added protection against pot breakage

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/EditToolVisualisingListener.kt
This creates an issue where it activates the delay timer when there's
nothing being visualised, making the visualiser not show up until the
claim tool is unequipped for a set amount of time.
=> Fixed visualiser triggering hide delay while not currently visualising

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/PermissionBehaviour.kt
This stops people from being able to put items in pots, which you can grant permission for using the manipulate permission.
=> Added protection against using pots

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/VisualisationServiceImpl.kt
If someone makes a claim in a donut shape leaving a middle section unclaimed, the visualiser does not show this and players could easily mistake that area as being claimed. This renders all inner borders in a similar manner to the outer border.
It may be useful to make the inner border a different colour in a more complex implementation, but API changes may need to be done to accommodate this. I will leave it as is for the patch fix.
=> Fixed visualiser not displaying inner border

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/ClaimBellListener.kt
All this does is cancel the interact event when the bell is being shift right click. This most importantly solves the trident duplication issue, but also makes it less annoying to interact with a bell when an item is being held in hand as it will use the item when the player is just trying to open the bell menu.
=> Fixed trident dupe and various other potential item interaction issues on bell usage

CHANGELOG.md, build.gradle.kts, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt, src/main/resources/plugin.yml
This issue is present in flags such as pistons or sculk spread, where if someone places the source block in one claim, it can have an effect in the other claim. The existing checks only take into account changes done outside of any claim affecting areas inside of a claim, not changes that could be done using an adjacent claim.
=> Fixed flag bypasses when actions done in adjacent claims affect another

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/domain/flags/Flag.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt
This affects concrete powder and lava as far as I'm aware. If fluids are placed outside of the current claim and flows into lava or concrete powder at the edge of a claim, it turns it into a different block. This is protected by the fluid flow flag.
=> Added protection against fluids forming blocks in claims

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/VisualisationServiceImpl.kt
Due to a certain math issue, some claims fail to be visualised, sending the function on an infinite loop that eventually crashes the server. This reworks the way the inner borders are calculated so that they are all obtained on the same function run, rather than being done on independent function runs that are likely to cause issues if done incorrectly.
=> Fixed crash occuring when visualiser is trying to render certain partition configurations

CHANGELOG.md, build.gradle.kts, src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/PermissionBehaviour.kt, src/main/resources/plugin.yml
Players should not be able to push animals or villagers around with wind charges without the Husbandry permission. This ensures that players cannot simply throw animals out of their pens and then steal or even kill them that way.
Players also should not be able to push armour stands around the same way, this makes sense as a build permission.
=> Added protection against wind charges pushing things around

CHANGELOG.md, build.gradle.kts, src/main/resources/plugin.yml
This just solves the inability to use the inventory GUI on servers of version 1.21.3
=> Update dependencies to support MC 1.21.3

CHANGELOG.md, build.gradle.kts, src/main/kotlin/dev/mizarc/bellclaims/BellClaims.kt, src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/persistence/Config.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/PermissionBehaviour.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/HarvestReplantListener.kt, src/main/kotlin/dev/mizarc/bellclaims/utils/PermissionDisplay.kt, src/main/resources/config.yml, src/main/resources/lang_EN.yml
Initially, the harvest permission was designed to cover sweet berries and glow berries since they weren't protected at all prior to this. As it didn't make sense to exclude other types of crops, a new system was implemented to allow players to harvest other types of crops by simply right clicking, which automatically replants the seeds as well. This was the easiest way around the issue of allowing players to harvest crops without being able to directly modify what crops are being grown in the farm. 
Bone meal on crops is also allowed as part of this permission, but not to other things such as grass.
=> Add harvesting permission and special harvester system for it

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PlayerClaimProtectionListener.kt
There was a present issue where if a claim is created at location (0, 0), the claim that exists at that location blocks creation and renaming of claims world wide. This also extends to other plugins that make use of custom anvil GUIs.
=> Fixed Anvil GUI check when location is 0, 0, 0

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PlayerClaimProtectionListener.kt
Players are now always able to hit armor stands, but cannot apply knockback or fire effects to it. Destroying armor stands still requires the Build permission.
=> Change armor stand protection behaviour

CHANGELOG.md, build.gradle.kts, src/main/kotlin/dev/mizarc/bellclaims/BellClaims.kt, src/main/kotlin/dev/mizarc/bellclaims/application/actions/claim/anchor/MoveClaimAnchor.kt, src/main/kotlin/dev/mizarc/bellclaims/application/actions/claim/partition/CanRemovePartition.kt, src/main/kotlin/dev/mizarc/bellclaims/application/actions/claim/partition/CreatePartition.kt, src/main/kotlin/dev/mizarc/bellclaims/application/actions/claim/partition/ResizePartition.kt, src/main/kotlin/dev/mizarc/bellclaims/application/actions/player/visualisation/DisplayVisualisation.kt, src/main/kotlin/dev/mizarc/bellclaims/application/services/PlayerMetadataService.kt, src/main/kotlin/dev/mizarc/bellclaims/application/services/scheduling/SchedulerService.kt, src/main/kotlin/dev/mizarc/bellclaims/di/Modules.kt, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/PlayerMetadataServiceVault.kt, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/scheduling/SchedulerServiceBukkit.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/ClaimAnchorListener.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/ClaimDestructionListener.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/EditToolListener.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/MoveToolListener.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/misc/EditToolMenu.kt, src/main/kotlin/dev/mizarc/bellclaims/utils/NonFullBlockFiltering.kt, src/main/resources/lang/defaults/en.properties
Administrators can now perform the following actions alongside building in claims when using /claimoverride:
- Breaking claim bell
- Accessing and editing claim settings
- Modifying the claim partitions using the claim tool
Fixes have also been applied in this PR to do with rendering the claims that you do not own and the messages that are displayed to you.
=> Allow admin override to perform all claim actions

CHANGELOG.md, src/main/kotlin/dev/mizarc/bellclaims/application/actions/claim/CreateClaim.kt, src/main/kotlin/dev/mizarc/bellclaims/application/actions/claim/IsNewClaimLocationValid.kt, src/main/kotlin/dev/mizarc/bellclaims/application/results/claim/CreateClaimResult.kt, src/main/kotlin/dev/mizarc/bellclaims/application/results/claim/IsNewClaimLocationValidResult.kt, src/main/kotlin/dev/mizarc/bellclaims/application/services/WorldManipulationService.kt, src/main/kotlin/dev/mizarc/bellclaims/domain/values/LocalizationKeys.kt, src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/WorldManipulationServiceBukkit.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/management/ClaimCreationMenu.kt, src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/management/ClaimNamingMenu.kt, src/main/resources/lang/defaults/en.properties
If the claim is too close to the world border and would result in the partition being outside of the border, the claim creation is blocked. This also solves a bug where partitions are oddly shaped when far away from world spawn due to floating point rounding issue.
=> Prevent claim from being created over world border
